<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.serializer.symfony' shared service.

return $this->privates['fos_rest.serializer.symfony'] = new \FOS\RestBundle\Serializer\SymfonySerializerAdapter(($this->services['serializer'] ?? $this->load('getSerializerService.php')));
