<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVAV89lM\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVAV89lM/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVAV89lM.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVAV89lM\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVAV89lM\srcDevDebugProjectContainer([
    'container.build_hash' => 'VAV89lM',
    'container.build_id' => 'c77cc5c0',
    'container.build_time' => 1578927192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVAV89lM');
